### ISSUE TITLE
"disagrees this is" sometimes showing disagreement with parent taxon of ID, not actual taxon of ID

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1676]
Two examples:

https://www.inaturalist.org/observations/10039273
<img width="668" alt="screen shot 2018-03-01 at 2 44 35 pm" src="https://user-images.githubusercontent.com/15896181/36873994-2837e5cc-1d5f-11e8-85eb-a90daa878d01.png">

https://www.inaturalist.org/observations/10018791
![image](https://user-images.githubusercontent.com/15896181/36874068-65e32990-1d5f-11e8-8cda-d059ff6946c9.png)

**Comment by tiwane** [comment]
bouteloua says "I have seen quite a few explicit disagreement issues such as this. They're usually fixed by "refreshing" the observation in some small way, e.g. voting and rescinding a DQA vote, adding/deleting a second ID."

**Comment by kueda** [comment]
...but any steps to reproduce? Does it happen consistently in any situation?

**Comment by tiwane** [comment]
No reports yet. I can take this down until we do but wanted to have a repository for it.

**Comment by carrieseltzer** [comment]
A variation, where edanko disagrees that it is flies, but selected a subsection of flies. edanko had the previous leading ID, then replaced it with a new ID, and now it is showing explicit disagreement with the parent taxon (instead of the earlier taxon).
 
https://www.inaturalist.org/observations/1971924
![screen shot 2018-03-02 at 11 35 50 am](https://user-images.githubusercontent.com/7501183/36910213-178a5dd6-1e0e-11e8-9e35-93773a52ec0f.png)

**Comment by kueda** [comment]
I was able to replicate and (I hope) fix Carrie's bug, but I still can't replicate the previous situations.

**Comment by tiwane** [comment]
I've asked cassi and Stephen to send me any details of how they made the IDs. cassi's pretty sure she made it directly on the observation (she's subscribed to the taxon) but doesn't remember much else.

Should we close until we get some more reports and can replicate?

**Comment by kueda** [comment]
Let's get these latest changes out first and see if they fix the problems I couldn't replicate.

**Comment by boucur** [comment]
https://www.inaturalist.org/observations/2665096
I can't remember what displayed immediately after making the ID.
I edited the ID comment field to add more text and that's when I noticed it.
Also, strangely, showing up as Casual.

**Comment by kueda** [comment]
I can't replicate this bug with the sequence of IDs displayed in any of the original obs reported. I'm pretty sure I fixed the one that Carrie reported. The last one Cassi reported seems to be working, right? Or if something weird happened it's not happening any more,
